server:
  port: 9002
  
spring:   
  # mysql setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-g66p7-kr.vpc-pub-cdb.ntruss.com:3306/bit701?serverTimezone=Asia/Seoul
    #url: jdbc:mysql://db-g66k8-kr.vpc-pub-cdb.ntruss.com:3306/bit701?serverTimezone=Asia/Seoul
    username: study
    password: bit123!@#
  servlet:
    multipart:
      max-file-size:
        20MB
 
    
# mybatis
mybatis:
  type-aliases-package: data.dto
  mapper-locations:
  - /mapper/**/*.xml